### ISSUE TITLE
Initialisation de la base H2

### ISSUE THREAD

**Issue by bilelkhalsi** [Remy-INOCO/Bank-Account-Kata#2]
Il y a Luiquibase/Flyway pour faire ça. En même temps ça permet d'avoir un jeu de données pour les testes d'integration.

`

	@Bean
	CommandLineRunner initDatabase(final UserRepository repository) {
		return args -> {
			LOGGER.info("Preloading {}", repository.save(new User("Bilbon", "Sacquet", 1500, "Test123")));
			LOGGER.info("Preloading {}", repository.save(new User("Frodon", "Sacquet", 1000, "Test123")));
			LOGGER.info("Preloading {}", repository.save(new User("Sam", "Gamegie", 5500, "Test123")));
		};
	}

`

**Comment by Remy-INOCO** [comment]
Dac je viens de regarder ce que c'étaient. J'ai compris que c'étaient plus des outils pour la migration de donnée nan ? Si c'est bien le cas, pour le kata, on m'a spécifié de ne pas faire de persistance, ceux pourquoi je suis parti là-dessus.

**Comment by bilelkhalsi** [comment]
En fait, ce sont des outils pour appliquer des changements sur une base de données tout en sauvegardant la version de la base à chaque changement. On les appelle souvent : des outils de versionning de la base.
Et ces outils fonctionnent aussi sur une base H2 (persistence in memory).
Les changements peuvent être :  des changements de schema (CREATE TABLE, DROP ...), des changements de données (INSERT, DELETE ...) ou juste l'initialisation de la base.

Je peux te pousser un exemple dans une branche si tu me donne l'accès.

**Comment by Remy-INOCO** [comment]
Oui je veux bien un exemple s'il te plait. Je t'ai envoyé une invitation :)

**Comment by bilelkhalsi** [comment]
cool :) merci !
 j'ai créé une Pull Request :
https://github.com/Remy-INOCO/Bank-Account-Kata/pull/9/files
