### ISSUE TITLE
Code Review : Swagger

### ISSUE THREAD

**Issue by bilelkhalsi** [Remy-INOCO/Bank-Account-Kata#8]
Pour une api, il faudrait toujours exposer un Swagger

**Comment by bilelkhalsi** [comment]
https://github.com/Remy-INOCO/Bank-Account-Kata/blob/99572a98ad9162b1addd66acd6a187c5f941ac66/Back-End/swagger.yaml#L1

Désolé de revenir sur ce point. Le swagger dont j'ai parlé c'est le swagger généré dynamiquement (configuré dans le code).
Peux-tu jeter un oeil sur cette library : https://springfox.github.io/springfox/docs/current/

**Comment by Remy-INOCO** [comment]
C'est bon je viens de push :)
